title: Colour palette inspiration
hero_image: images/banner.png
description: Colour palette inspiration for the senseHAT LED array
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Colour palette inspiration
